version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    depends_on:
      - ollama
      # - redis
    restart: unless-stopped

  # worker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.backend
  #   command: dramatiq tasks
  #   depends_on:
  #     - backend
  #     - redis
  #   environment:
  #     - FLASK_ENV=development
  #   restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    restart: unless-stopped

  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    
    runtime: nvidia    #comment-out this if your device doesnot support gpu
    restart: unless-stopped

volumes:
  ollama-data:
