# Dockerfile.frontend
FROM node:20 as build

WORKDIR /app

# Install and build
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ .
RUN npm run build

# Serve static files using nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
